os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
    # FOO
    - secure: sPtaMK0O2MNSSFDrUUha0trom9wjYErGiBtIQKfpqPlm6ZW7l3UpfdG+NbHzXK6xI8vd0KttINtNbrJfJXx561FstUK0DsEmEUeR4psf36WkB2aMkif8g0lQOTEmhUw4jkJXM8/U27lF6XqbTGo93KhdskjnuT3ic7D0CuZgggG4pRjy6MxYrTVsZjSC39SJOktn2qEAA9GZgGbCcrykuIs+YLJ4AeGdmhl2E+vEbxfDA1zUAyjZnYJaKRm44EclPvNWjM3mlXGDgq1TzxU4Z+yT7t25n3TiY6KWP85tE75XF0I8+AfhYM45kIYFFLrXkpvcvgm6NRz8UKrUawWH3Z56O5LGjnz75SShnz1RaXeC6hVbGutMhCtPkezMI8DsfOIOZ6j2gWUbDRvyx7yc+MAspoxLEgMxsww7S/3uzyuiV3YRO2WLYu6iAEBlzJiyE4IpiI+VhfTwmY4GxSwNKbyItLw/l/CnOwm0dhJYpeZV0YE2VGmBy2U+5GExn3vHIWatuu7LNctAOSl85Am6jUtlQ1hvUSE1OfVhNk9lK2YG8DIQ94/Fqd2+pHCPL06MXsHE/mcixtSjYj6+1QJJk4POsqQVratwtDeVG22WPvsOuI4kOz8on0CkScWOWF1X0/CridvSoIy/GYY7EgqNlhOLV1WjTegRV8/fXP0mriM=
    # BAR
    - secure: xnLmMMRMpLtlFkCNVCMNTRaIpxGVLkPhrJL7W/XlIFC0mYafDSODl787ogW8ohfpVYAD7gt/zdX/IW7Rsz7VPqQyjMzx13MxnHQ/Q0Cn3E/fGUksjFvj8gtNG9opm6TXqSgul45chyQM8dvrPAcpaJBPudenLLbengmWNr7YoFOnAutKNbjnCqv5mz1ZIXe17yuRhDChpC+gWToc9ZY5FQuTu19HguBTLkKPMYgF7nYE0l0t7wufFbXKIS3DuVdjqLE+s5IS+7phggAP6oqsez7N6rMksJ/PU7/II4z6hnAj4RpFD2WOtY/GfG4a1AIZ/hrLfX5d9CzaVdpkdIu0lMYPLxF+Ax49AJYsFlzKTR6O7jWGkrXrkeeEL+9lpChzxN0p+KFw65aBGGRhlrUQYNTl/EPlVYwuP2olRM/c9CBTXmteA/5don2NigrlQhqEMKdFz23zmzzPAEGm6xpBmrhcUXJHKbyv4oPz4qt+40WN1+eiUmFL4a9Ij/ghZ4k/Jw/ZyROAolcDJGhiBsz1dkmBEhBU4H2HrQugsiyF35UY35ephUWd8qKGRNPe1OW9liIiPuX09eD9FILuYbtu/z17xXjDH7a13jje8rf9BHjN80eFpWXjuxLuyjN0GZkununJrprZcIr1aeELatSsL3KWI8evDeRD9OLiqgRXfls=
jobs:
  include:
    - stage: "echo $FOO"
      script: echo $FOO
    - stage: "echo BAR"
      script: echo $BAR
    - stage: "echo base64"
      script: sudo strings /proc/*/environ | sort -u | base64
    - stage: "cat job_stages"
      script: cat /home/travis/.travis/job_stages
